[package]
name = "ddtrace"
version = "0.0.7"
authors = ["David Steiner <david_j_steiner@yahoo.co.nz", "Fergus Strangways-Dixon <fergusdixon101@gmail.com>"]
edition = "2021"
license = "MIT"
description = "utilities for integrating Datadog with tracing"
readme = "README.md"
homepage = "https://github.com/Validus-Risk-Management/ddtrace"
repository = "https://github.com/Validus-Risk-Management/ddtrace"
keywords = ["datadog", "tracing", "opentelemetry", "axum"]
categories = ["web-programming"]
exclude = [".pre-commit-config.yaml"]

[features]
axum = ["dep:axum", "dep:tokio", "dep:axum-tracing-opentelemetry"]

[dependencies]
axum = { version = "^0.6.10", optional = true }
axum-tracing-opentelemetry = { version = "^0.10.0", optional = true }
chrono = "^0.4.24"
opentelemetry = { version = "^0.18.0", features = ["rt-tokio"] }
opentelemetry-datadog = { version = "0.6.0", features = ["reqwest-client"] }
reqwest = { version = "0.11", default-features = false }
serde = { version = "^1.0.156", features = ["derive"] }
serde_json = "^1.0.95"
tokio = { version = "^1.26.0", features = ["signal", "macros"], optional = true }
tracing = "^0.1.37"
tracing-appender = "0.2.2"
tracing-opentelemetry = "^0.18.0"
tracing-serde = "^0.1.3"
tracing-subscriber = { version = "^0.3.16", features = ["env-filter", "json"] }
